[package]
name = "sqlite2parquet"
description = "Generate parquet files from sqlite databases"
version = "0.4.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2021"
license = "Unlicense"
repository = "https://github.com/asayers/sqlite2parquet"

[dependencies]
anyhow = "1.0.52"
# Chrono is not a direct dependency; it's a dependency of "parquet".  However,
# parquet's Cargo.toml is slightly buggy, so if we don't specify chrono here
# then parquet fails to compile.
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
crossterm = { version = "0.23.0", optional = true }
fallible-streaming-iterator = "0.1.9"
parquet = { version = "9.0.2", default-features = false, features = ["zstd"] }
parquet-format = "4.0.0"
rusqlite = "0.26.1"
structopt = { version = "0.3.25", optional = true }
thousands = { version = "0.2.0", optional = true }

[features]
cli = ["crossterm", "structopt", "thousands"]
default = ["cli"]
