[package]
name = "sqlite2parquet"
description = "Generate parquet files from sqlite databases"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2021"
license = "Unlicense"
repository = "https://github.com/asayers/sqlite2parquet"

[dependencies]
anyhow = "1.0.52"
crossterm = "0.22.1"
fallible-streaming-iterator = "0.1.9"
parquet = "7.0.0"
parquet-format = "4.0.0"
rusqlite = "0.26.1"
structopt = "0.3.25"
thousands = "0.2.0"
