[package]
name = "sqlite2parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
crossterm = "0.22.1"
fallible-streaming-iterator = "0.1.9"
parquet = "6.2.0"
parquet-format = "2.6.1"
rusqlite = "0.26.1"
structopt = "0.3.25"
thousands = "0.2.0"
